name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main # Triggered on PR creation or updates to PRs targeting the main branch
  push:
    branches:
      - main # Triggered only when a PR is merged into the main branch

jobs:
  integration-test:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies
        working-directory: backend
        run: npm install

      - name: Make Scripts Executable
        run: |
          chmod +x backend/scripts/run-integration.sh
          chmod +x backend/scripts/wait-for-it.sh

      - name: Setup PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql postgresql-contrib
          sudo systemctl start postgresql
          sudo -u postgres psql -c "CREATE DATABASE ${{ secrets.DB_NAME }};"
          sudo -u postgres psql -c "ALTER USER ${{ secrets.DB_USER }} WITH PASSWORD '${{ secrets.DB_PASSWORD }}';"

      - name: Apply Prisma Migrations
        working-directory: backend
        run: npx prisma migrate dev --name init

      - name: Run Integration Tests
        working-directory: backend
        run: npm run test:integration

  build-artifact:
    name: Build Application Artifact
    runs-on: ubuntu-latest
    needs: integration-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies & Build Application
        working-directory: backend
        run: |
          npm install
          npm run build
          zip -r backend.zip .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifact
          path: backend/backend.zip

  packer-build:
    name: Build Custom Image with Packer (AWS & GCP)
    runs-on: ubuntu-latest
    needs: build-artifact
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-artifact
          path: backend

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup GCP CLI
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_CREDENTIALS }}

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"

      - name: Initialize Packer Plugins
        env:
          PACKER_GITHUB_API_TOKEN: ${{ secrets.PACKER_GITHUB_API_TOKEN }}
        run: packer init .

      - name: Validate Packer Template
        run: packer validate machine.pkr.hcl

      - name: Build Custom Images
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GCP_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_CREDENTIALS }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          # Generate timestamp (ISO 8601 format without colons)
          BUILD_TIMESTAMP=$(date -u +"%Y%m%dT%H%M%S")

          # Run Packer build
          packer build \
            -var "DATABASE_URL=${{ secrets.DATABASE_URL }}" \
            -var "build_timestamp=$BUILD_TIMESTAMP" \
            machine.pkr.hcl | tee packer-output.txt

      - name: Extract AMI ID
        id: ami
        run: |
          AMI_ID=$(grep 'artifact,0,id' packer-output.txt | cut -d',' -f6 | cut -d':' -f2)
          echo "ami_id=$AMI_ID" >> $GITHUB_OUTPUT

  deploy-demo:
    name: Deploy to DEMO Account
    runs-on: ubuntu-latest
    needs: packer-build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure DEMO AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.DEMO_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEMO_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update Launch Template
        run: |
          LATEST_VERSION=$(aws ec2 describe-launch-templates --launch-template-ids ${{ secrets.DEMO_LAUNCH_TEMPLATE_ID }} --query 'LaunchTemplates[0].LatestVersionNumber' --output text)
          aws ec2 create-launch-template-version \
            --launch-template-id ${{ secrets.DEMO_LAUNCH_TEMPLATE_ID }} \
            --source-version $LATEST_VERSION \
            --launch-template-data "{\"ImageId\": \"${{ needs.packer-build.outputs.ami_id }}\"}"

      - name: Trigger Instance Refresh
        run: |
          aws autoscaling start-instance-refresh \
            --auto-scaling-group-name ${{ secrets.DEMO_ASG_NAME }} \
            --preferences '{"MinHealthyPercentage": 90, "InstanceWarmup": 300}'

      - name: Wait for Instance Refresh
        run: |
          while true; do
            STATUS=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name ${{ secrets.DEMO_ASG_NAME }} --query 'InstanceRefreshes[0].Status' --output text)
            if [ "$STATUS" = "Successful" ]; then
              echo "Instance refresh succeeded"
              break
            elif [ "$STATUS" = "Failed" ] || [ "$STATUS" = "Cancelling" ] || [ "$STATUS" = "Cancelled" ]; then
              echo "Instance refresh failed with status: $STATUS"
              exit 1
            fi
            echo "Waiting for instance refresh..."
            sleep 30
          done

  # share-images:
  #   name: Share AWS AMI & GCP Image with Demo Accounts/Projects
  #   runs-on: ubuntu-latest
  #   needs: packer-build
  #   steps:
  #     - name: Setup GCP CLI
  #       uses: google-github-actions/auth@v2
  #       with:
  #         credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_CREDENTIALS }}

  #     - name: Share GCP Image with Demo Project
  #       run: |
  #         echo "Sharing GCP Image ${{ secrets.GCP_IMAGE_NAME }} with Demo Project..."
  #         gcloud compute images add-iam-policy-binding ${{ secrets.GCP_IMAGE_NAME }} \
  #           --project=${{ secrets.GCP_PROJECT_ID }} \
  #           --member="user:${{ secrets.GCP_DEMO_ACCOUNT_EMAIL }}" \
  #           --role="roles/compute.imageUser"
