name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main # Triggered on PR creation or updates to PRs targeting the main branch
  push:
    branches:
      - main # Triggered only when a PR is merged into the main branch

jobs:
  # Integration Testing Job
  integration-test:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies
        working-directory: backend
        run: npm install

      - name: Make Scripts Executable
        run: |
          chmod +x backend/scripts/run-integration.sh
          chmod +x backend/scripts/wait-for-it.sh

      - name: Setup PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql postgresql-contrib
          sudo systemctl start postgresql
          sudo -u postgres psql -c "CREATE DATABASE ${{ secrets.DB_NAME }};"
          sudo -u postgres psql -c "ALTER USER ${{ secrets.DB_USER }} WITH PASSWORD '${{ secrets.DB_PASSWORD }}';"

      - name: Apply Prisma Migrations
        working-directory: backend
        run: npx prisma migrate dev --name init

      - name: Run Integration Tests
        working-directory: backend
        run: npm run test:integration

  # Build Application Artifact
  build-artifact:
    name: Build Application Artifact
    runs-on: ubuntu-latest
    needs: integration-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Only on merge
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies & Build Application
        working-directory: backend
        run: |
          npm install
          npm run build
          zip -r backend.zip .

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-artifact
          path: backend/backend.zip

  # Packer Build Job (only runs on merges to main)
  packer-build:
    name: Build Custom Image with Packer (AWS & GCP)
    runs-on: ubuntu-latest
    needs: build-artifact
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Runs only on merge to main
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-artifact
          path: backend

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup GCP CLI
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{secrets.GCP_SERVICE_ACCOUNT_CREDENTIALS}}

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"

      - name: Initialize Packer Plugins
        env:
          PACKER_GITHUB_API_TOKEN: ${{ secrets.PACKER_GITHUB_API_TOKEN }}
        run: packer init .

      - name: Validate Packer Template
        run: packer validate machine.pkr.hcl

      - name: Build Custom Image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          # Generate timestamp (ISO 8601 format without colons)
          BUILD_TIMESTAMP=$(date -u +"%Y%m%dT%H%M%S")

          # Pass timestamp to Packer
          packer build \
            -var "build_timestamp=$BUILD_TIMESTAMP" \
            machine.pkr.hcl


